name: Release Extension
run-name: Release Extension

on:
  workflow_dispatch:

concurrency:
  group: "release-extension"
  cancel-in-progress: true

jobs:
  bump-version:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 #v6.2.0
        with:
          node-version-file: .nvmrc

      - run: npm ci
      - run: npx semantic-release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Firefox Sign and Publish
        if: steps.semantic-release.outputs.new_release_published == 'true'
        # Don't fail the workflow if this step fails, as
        # it will always fails for the initial release and
        # for subsequent releases we can recover by manually uploading the
        # unsigned extension to AMO.
        continue-on-error: true
        env:
          AMO_API_KEY: ${{ secrets.AMO_API_KEY }}
          AMO_API_SECRET: ${{ secrets.AMO_API_SECRET }}
        run: |
          ./scripts/release/firefox-publish.sh
          gh release upload ${{ steps.semantic-release.outputs.next_release_version }} dist/*.xpi --clobber
